#Spring cloud config
spring:   
  cloud: 
    config:
      server:
        git:
          uri: https://github.com/wadehe1982/cloudconfig.git
          
server:
  context-path: /configserver
  port: 9999